### PR TITLE
To fix #7

### LINKED ISSUE #7: Glitch in event
`PlayerInteractEvent` **should be** `Cancelled`

Otherwise, when purchase will be placed block before sign

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by Pub4Game** [comment]
Error in _Travis C_

**Comment by onebone** [comment]
Does this change block placing?

**Comment by Pub4Game** [comment]
Yes, only when interacts with shop

**Comment by onebone** [comment]
I have tested, I think it doesn't block placing.

I am now working on it, but I am working on mobile so it is too hard to modify the code. Could you make another commit to block placing?

**Comment by Pub4Game** [comment]
It blocks a placement block, when you click on a sign. This code is 100% working, it is on my server.

**Comment by onebone** [comment]
Ah, my mistake. Thanks!

**Pull request merged**
