### PR TITLE
Small improvement

### PR DESCRIPTION
**Pull request by Pub4Game**
@onebone 
- Fixed a CRITICAL bug with buying items

### CODE REVIEW

**Comment by onebone** [comment]
What is critical bug of that line?
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/inventory/BaseInventory.java#L265

Or is there any other problem?

**Comment by Pub4Game** [comment]
Items should be issued with variable data (meta, count)

**Comment by onebone** [comment]
Can you tell me the difference between two codes?

**Comment by Pub4Game** [comment]
For example:
SHOP
100
17:3
32
You code give - 17 - 1

My code give 17:3 - 32

**Comment by Pub4Game** [comment]
Ah, I hadn't noticed... Why you in Shop do it? Maybe I want to use it as an API and get only Item?

**Pull request closed without merging**
